const provinceList = [
    {domain: "Aceh", area_id: "501397", description: "Banda Aceh"},
    {domain: "Bali", area_id: "501164", description: "Denpasar"},
    {domain: "Banten", area_id: "501174", description: "Serang"},
    {domain: "Bengkulu", area_id: "501178", description: "Bengkulu"},
    {domain: "DI Yogyakarta", area_id: "501190", description: "Yogyakarta"},
    {domain: "DKI Jakarta", area_id: "501195", description: "Jakarta Pusat"},
    {domain: "Gorontalo", area_id: "501197", description: "Gorontalo"},
    {domain: "Jambi", area_id: "501205", description: "Jambi"},
    {domain: "Jawa Barat", area_id: "501212", description: "Bandung"},
    {domain: "Jawa Tengah", area_id: "501262", description: "Semarang"},
    {domain: "Jawa Timur", area_id: "501306", description: "Surabaya"},
    {domain: "Kalimantan Barat", area_id: "501315", description: "Pontianak"},
    {domain: "Kalimantan Tengah", area_id: "501342", description: "Palangkaraya"},
    {domain: "Kalimantan Timur", area_id: "501354", description: "Samarinda"},
    {domain: "Kalimantan Utara", area_id: "501342", description: "Tarakan"},
    {domain: "Kep. Bangka Belitung", area_id: "501365", description: "Pangkal Pinang"},
    {domain: "Kep. Riau", area_id: "501371", description: "Tanjung Pinang"},
    {domain: "Maluku", area_id: "501382", description: "Ambon"},
    {domain: "Maluku Utara", area_id: "501394", description: "Ternate"},
    {domain: "Nusa Tenggara Barat", area_id: "501421", description: "Mataram"},
    {domain: "Nusa Tenggara Timur", area_id: "501434", description: "Kupang"},
    {domain: "Papua", area_id: "501447", description: "Kota Jayapura"},
    {domain: "Papua Barat", area_id: "501467", description: "Manokwari"},
    {domain: "Riau", area_id: "501478", description: "Pekanbaru"},
    {domain: "Sulawesi Barat", area_id: "501485", description: "Mamuju"},
    {domain: "Sulawesi Selatan", area_id: "501495", description: "Makassar"},
    {domain: "Sulawesi Tengah", area_id: "1200106", description: "Palu"},
    {domain: "Sulawesi Tenggara", area_id: "5013053", description: "Ambon"},
    {domain: "Sulawesi Utara", area_id: "501534", description: "Manado"},
    {domain: "Sumatera Barat", area_id: "501545", description: "Padang"},
    {domain: "Sumatera Selatan", area_id: "501568", description: "Palembang"},
    {domain: "Sumatera Utara", area_id: "501580", description: "Medan"},
]

module.exports = provinceList;